### ISSUE TITLE
can't cd to caffe-tensorflow

### ISSUE THREAD

**Issue by ghost** [ivanzhovannik/convert_caffe_windows#1]
/bin/sh: 1: cd: can't cd to caffe-tensorflow while executing command "docker run -v $pwd/converted:/workspace -ti newimage" 

System 
OS :Windows 10

**Comment by ivanzhovannik** [comment]
> /bin/sh: 1: cd: can't cd to caffe-tensorflow while executing command "docker run -v $pwd/converted:/workspace -ti newimage"
> 
> System
> OS :Windows 10

Hey @iram01 thanks a lot for reaching out. Sorry, I did not check the software for a while. If possible, could you please give me  sample `.caffemodel` and `.prototxt` files for conversion? So that I can try to reproduce your case on Windows 10.

**Comment by ghost** [comment]
> > /bin/sh: 1: cd: can't cd to caffe-tensorflow while executing command "docker run -v $pwd/converted:/workspace -ti newimage"
> > System
> > OS :Windows 10
> 
> Hey @iram01 thanks a lot for reaching out. Sorry, I did not check the software for a while. If possible, could you please give me sample `.caffemodel` and `.prototxt` files for conversion? So that I can try to reproduce your case on Windows 10.

caffemodel -  http://dl.yf.io/dilation/models/dilation8_pascal_voc.caffemodel
.prototxt - https://raw.githubusercontent.com/fyu/dilation/master/models/dilation8_pascal_voc_deploy.prototxt

**Comment by ivanzhovannik** [comment]
I've tried to use the links to reproduce the error and I currently get the following traceback after running `docker run -v $pwd/converted:/workspace -ti newimage`:

```
Cloning into 'caffe-tensorflow'...
remote: Enumerating objects: 479, done.
remote: Total 479 (delta 0), reused 0 (delta 0), pack-reused 479
Receiving objects: 100% (479/479), 1.71 MiB | 0 bytes/s, done.
Resolving deltas: 100% (275/275), done.
Checking connectivity... done.
--2021-08-13 16:47:28--  http://dl.yf.io/dilation/models/dilation8_pascal_voc.caffemodel
Resolving dl.yf.io (dl.yf.io)... 128.32.162.150
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 564602191 (538M) [application/octet-stream]
Saving to: '/workspace/caffe-tensorflow/dilation8_pascal_voc.caffemodel'

dilation8_pascal_voc.caffemod 100%[=================================================>] 538.45M  3.11MB/s    in 1m 59s

2021-08-13 16:49:27 (4.52 MB/s) - '/workspace/caffe-tensorflow/dilation8_pascal_voc.caffemodel' saved [564602191/564602191]

--2021-08-13 16:49:27--  https://raw.githubusercontent.com/fyu/dilation/master/models/dilation8_pascal_voc_deploy.prototxt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6630 (6.5K) [text/plain]
Saving to: '/workspace/caffe-tensorflow/dilation8_pascal_voc_deploy.prototxt'

dilation8_pascal_voc_deploy.p 100%[=================================================>]   6.47K  --.-KB/s    in 0s

2021-08-13 16:49:28 (19.0 MB/s) - '/workspace/caffe-tensorflow/dilation8_pascal_voc_deploy.prototxt' saved [6630/6630]

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./convert.py", line 60, in <module>
    main()
  File "./convert.py", line 56, in main
    args.phase)
  File "./convert.py", line 27, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/workspace/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "/workspace/caffe-tensorflow/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/workspace/caffe-tensorflow/kaffe/graph.py", line 140, in __init__
    self.load()
  File "/workspace/caffe-tensorflow/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/workspace/caffe-tensorflow/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/workspace/caffe-tensorflow/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "/workspace/caffe-tensorflow/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "/workspace/caffe-tensorflow/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 732, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```

I will try to look more into the bug

UPD: [here in original *caffe-tensorflow* repo](https://github.com/ethereon/caffe-tensorflow/issues/114) several people did address the same issue. I have cloned and altered the original code at https://github.com/ivanzhovannik/caffe-tensorflow

**Comment by ghost** [comment]
but I got error " /bin/sh: 1: cd: can't cd to caffe-tensorflow" for the command " docker run -v $pwd/converted:/workspace -ti newimage"

**Comment by ivanzhovannik** [comment]
> but I got error " /bin/sh: 1: cd: can't cd to caffe-tensorflow" for the command " docker run -v $pwd/converted:/workspace -ti newimage"

@iram01 could you please:
1. Copy the whole log message your powershell or cmd? The `wget` lines did work, I assume...
2. Alter the `Dockerfile` for [these example files](https://github.com/ivanzhovannik/caffe-tensorflow/tree/master/examples/mnist) - does it work properly on them? TO perform it replace the `.prototxt` and `.caffemodel` files with :
```
wget https://raw.githubusercontent.com/ivanzhovannik/caffe-tensorflow/master/examples/mnist/lenet_iter_10000.caffemodel
wget https://raw.githubusercontent.com/ivanzhovannik/caffe-tensorflow/master/examples/mnist/lenet.prototxt
```
3. Check which images you have by running `docker image ls`. You should have `bvlc/caffe` and `newimage`

**Comment by ivanzhovannik** [comment]
Hey @iram01 - the conversion works now on my machine, `Windows 10, Docker version 20.10.7, build f0df350` - I have pushed the Dockerfile in the *#1_fix* branch merge pull request.

Please tell me if that worked for you.

**Comment by iram01** [comment]
PS C:\Users\DGRE\segmentation_keras> docker build . -t newimage
[+] Building 7.9s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                     
 => => transferring dockerfile: 32B                                                                                                                                                      
 => [internal] load .dockerignore                                                                                                                                                        
 => => transferring context: 2B                                                                                                                                                          
 => [internal] load metadata for docker.io/bvlc/caffe:cpu                                                                                                                                
 => [auth] bvlc/caffe:pull token for registry-1.docker.io                                                                                                                                
 => [1/2] FROM docker.io/bvlc/caffe:cpu@sha256:1dd685def250ef965599c2794508aeddf8c4b91447c2e923ac0bf5e8ecf2a499                                                                          
 => CACHED [2/2] RUN pip install tensorflow                                                                                                                                              
 => exporting to image                                                                                                                                                                   
 => => exporting layers                                                                                                                                                                  
 => => writing image sha256:7412e10235a03900212d03c052763e2ae1a71788c10b901921f245ca5fd717f1                                                                                             
 => => naming to docker.io/library/newimage                                                                                                                                              
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

PS C:\Users\DGRE\segmentation_keras> docker run -v $pwd/converted:/workspace -ti newimage
/bin/sh: 1: cd: can't cd to caffe-tensorflow

PS C:\Users\DGRE\segmentation_keras> docker --version
Docker version 20.10.7, build f0df350

Same error after making changes to Dockerfile and .gitignore

**Comment by ghost** [comment]
docker build . -t newimage
                                                                                                                              
[+] Building 7.4s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                     
 => => transferring dockerfile: 32B                                                                                                                                                      
 => [internal] load .dockerignore                                                                                                                                                        
 => => transferring context: 2B                                                                                                                                                          
 => [internal] load metadata for docker.io/bvlc/caffe:cpu                                                                                                                                
 => [auth] bvlc/caffe:pull token for registry-1.docker.io                                                                                                                                
 => [1/2] FROM docker.io/bvlc/caffe:cpu@sha256:1dd685def250ef965599c2794508aeddf8c4b91447c2e923ac0bf5e8ecf2a499                                                                          
 => CACHED [2/2] RUN pip install tensorflow                                                                                                                                              
 => exporting to image                                                                                                                                                                   
 => => exporting layers                                                                                                                                                                  
 => => writing image sha256:7412e10235a03900212d03c052763e2ae1a71788c10b901921f245ca5fd717f1                                                                                             
 => => naming to docker.io/library/newimage                                                                                                                                              
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

docker run -v $pwd/converted:/workspace -ti newimage
/bin/sh: 1: cd: can't cd to caffe-tensorflow

docker --version
Docker version 20.10.7, build f0df350

Same error after making changes to Dockerfile and .gitignore

**Comment by ghost** [comment]
Instead of giving command cd caffe-tensorflow in dockerfile ,I tried to execute the command directly in the folder caffe-tensorflow and this worked for me but now this command execution killed as shown below.....can you please help me either this error due to memory or there is some other problem

docker run -v $pwd/converted:/workspace -ti image3
--2021-08-27 22:20:41--  http://dl.yf.io/dilation/models/dilation8_pascal_voc.caffemodel
Resolving dl.yf.io (dl.yf.io)... 128.32.162.150
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 564602191 (538M) [application/octet-stream]
Saving to: '/workspace/caffe-tensorflow/dilation8_pascal_voc.caffemodel'

dilation8_pascal_voc.caffemodel.1               100%[=====================================================================================================>] 538.45M  3.38MB/s    in 3m 46s

2021-08-27 22:24:30 (2.39 MB/s) - '/workspace/caffe-tensorflow/dilation8_pascal_voc.caffemodel.1' saved [564602191/564602191]

--2021-08-27 22:24:30--  https://raw.githubusercontent.com/fyu/dilation/master/models/dilation8_pascal_voc_deploy.prototxt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6630 (6.5K) [text/plain]
Saving to: '/workspace/caffe-tensorflow/dilation8_pascal_voc_deploy.prototxt'

dilation8_pascal_voc_deploy.prototxt.1          100%[=====================================================================================================>]   6.47K  --.-KB/s    in 0.004s

2021-08-27 22:24:31 (1.70 MB/s) - '/workspace/caffe-tensorflow/dilation8_pascal_voc_deploy.prototxt.1' saved [6630/6630]

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Killed

**Comment by ivanzhovannik** [comment]
@iram01 sorry, I was busy with my job search and thesis preparation. Have you found a solution or there is still this problem in existence?
